 language: node_js

 node_js:
  - "0.12.7"

 branches:
   only:
   - engine


 install:
 - npm install hexo-cli -g
 - npm install hexo --save
 - npm install

 script:
 - hexo clean
 - hexo generate
 - hexo deploy
