language: node_js

node_js:
- "0.12.7"

branches:
 only:
- engine

before_install:
- openssl aes-256-cbc -K $encrypted_9d9975ecae4c_key -iv $encrypted_9d9975ecae4c_iv
  -in id_rsa.enc -out c:\\Users\\Chao\\.ssh\\id_rsa -d

install:
- npm install hexo-cli -g
- npm install hexo --save
- npm install

script:
- hexo clean
- hexo generate
- hexo deploy
