 language: node_js

 node_js:
  - "0.12.7"

 branches:
   only:
   - engine


 install:
 - npm install hexo-cli -g
 - npm install hexo --save
 - npm install

 script:
 -git config --global user.email "373446951@qq.com"
 -git config --global user.name "bob12358"
 - hexo clean
 - hexo generate
 - hexo deploy
